name = "MultiThreadedCaches"
uuid = "18056a9e-ed0c-4ef3-9ad7-376a7fb08032"
authors = ["Nathan Daly <nhdaly@gmail.com> and contributors"]
version = "0.1.2"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
